Test build outdated

diff --git a/.github/workflows/build-matterbridge-plugin.yml b/.github/workflows/build-matterbridge-plugin.yml
--- a/.github/workflows/build-matterbridge-plugin.yml
+++ b/.github/workflows/build-matterbridge-plugin.yml
@@ -22,7 +22,7 @@ jobs:
           node-version: ${{ matrix.node-version }}
 
       - name: Install matterbridge
-        run: npm -g install matterbridge
+        run: npm install -g matterbridge
 
       - name: Install dependencies
         run: npm install
@@ -32,4 +32,12 @@ jobs:
 
       - name: Build the project
         run: npm run build
+
+      - name: List, audit, fix outdated dependencies and build again
+        run: |
+          npm list --outdated
+          npm audit || true  # ignore failures
+          npm audit fix || true
+          npm list --outdated
+          npm run build
 
